### ISSUE TITLE
Can I use it on Ubuntu?

### ISSUE THREAD

**Issue by trappedinspacetime** [kyx0r/xkeyboard#1]
First of all I congratulate you on your project. I am on Ubuntu 20.04 Mate Desktop. I was not able to build it via `Makefile`, I built it  in command line, but when I run it, no `gui` comes up.

**Comment by kyx0r** [comment]
Have you checked the left bottom corner of your screen? When you run xkeyboard it starts in "minimized" mode, there should be a 16x16 px icon, if you click it the gui will unfold.

Yes, ubuntu is probably the most non linux world / spec compliant distro out there. The reason makefile did not work was probably because they stuff compiler includes into non standard directories or something even worse. But if you still managed to build it, and nothing shows up, most likely it's because xkeyboard creates a standalone window that is flagged to not be managed by any window manager or desktop environment of sorts. So might get "displayed" below your Mate Desktop. Although I have designed it to always set itself on top of everything else there may still be an outlier like this. I would suggest to not run any desktop environment and try a window manager instead, see how it works on a more minimal and simple system. I can't really help you troubleshoot this because I run xserver + dwm. You can find my custom dwm in klec repo and build it. Although dwm is not really required here. Xorg + Xterm can also hold a valid session.

**Comment by trappedinspacetime** [comment]
Wow, it works like a charm. I like it. I didn't notice that tiny icon. Thank you for your help. I must say that it's a professional work. Congratulations again. I hope you add it to Ubuntu repositories.
All the best.
